/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/detail/': RouteRecordInfo<'/detail/', '/detail', Record<never, never>, Record<never, never>>,
    '/detail/intro-dialog': RouteRecordInfo<'/detail/intro-dialog', '/detail/intro-dialog', Record<never, never>, Record<never, never>>,
    '/detail/play-util': RouteRecordInfo<'/detail/play-util', '/detail/play-util', Record<never, never>, Record<never, never>>,
    '/detail/playlist-dialog': RouteRecordInfo<'/detail/playlist-dialog', '/detail/playlist-dialog', Record<never, never>, Record<never, never>>,
    '/home/': RouteRecordInfo<'/home/', '/home', Record<never, never>, Record<never, never>>,
  }
}
