/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LoadingSkeleton: typeof import('./components/skeleton/loading-skeleton.vue')['default']
    PlayList: typeof import('./components/list/play-list.vue')['default']
    RecommendList: typeof import('./components/list/recommend-list.vue')['default']
    RelateList: typeof import('./components/list/relate-list.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollWrap: typeof import('./components/scroll/scroll-wrap.vue')['default']
    SearchHistory: typeof import('./components/search/search-history.vue')['default']
    SearchSkeleton: typeof import('./components/search/search-skeleton.vue')['default']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VideoList: typeof import('./components/list/video-list.vue')['default']
    VideoSearch: typeof import('./components/search/video-search.vue')['default']
  }
}
