// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LoadingSkeleton: typeof import('./components/skeleton/loading-skeleton.vue')['default']
    PlayList: typeof import('./components/list/play-list.vue')['default']
    RecommendList: typeof import('./components/list/recommend-list.vue')['default']
    RelateList: typeof import('./components/list/relate-list.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollWrap: typeof import('./components/scroll/scroll-wrap.vue')['default']
    SearchHistory: typeof import('./components/search/search-history.vue')['default']
    SearchSkeleton: typeof import('./components/search/search-skeleton.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCol: typeof import('vant/es')['Col']
    VanEmpty: typeof import('vant/es')['Empty']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanPopover: typeof import('vant/es')['Popover']
    VanRow: typeof import('vant/es')['Row']
    VanSearch: typeof import('vant/es')['Search']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanTag: typeof import('vant/es')['Tag']
    VideoList: typeof import('./components/list/video-list.vue')['default']
    VideoSearch: typeof import('./components/search/video-search.vue')['default']
  }
}
